pipeline:
    triggerCD:
        image: 'node:6.9.5'
        environment:
            - SOAJS_CD_AUTH_KEY=${SOAJS_CD_AUTH_KEY}
            - SOAJS_CD_DEPLOY_TOKEN=${SOAJS_CD_DEPLOY_TOKEN}
            - SOAJS_CD_DASHBOARD_DOMAIN=${SOAJS_CD_DASHBOARD_DOMAIN}
            - SOAJS_CD_API_ROUTE=${SOAJS_CD_API_ROUTE}
            - SOAJS_CD_DASHBOARD_PORT=${SOAJS_CD_DASHBOARD_PORT}
            - SOAJS_CD_DASHBOARD_PROTOCOL=${SOAJS_CD_DASHBOARD_PROTOCOL}
        when:
            status: [success]
        commands:
            - npm install request
            - 'node ./soajs.cd.js'
